### ISSUE TITLE
No sabemos como representar un reto

### ISSUE THREAD

**Issue by JaimeGM96** [chelunike/didactic-chainsaw#10]
Relacionado con #2. Hace referencia a lo nombrado en #5.

**Comment by JaimeGM96** [comment]
¿Qué información tiene un reto?

**Comment by chelunike** [comment]
@JaimeGM96 Un reto podria contener como datos:

- IP
- PUERTO
- SO
- Versión
- Flag (si se consigue :)

**Comment by JaimeGM96** [comment]
Entonces, lo que íbamos a representar en una flag, como hemos comentado en #8, lo pasamos al modelo del reto.

**Comment by JaimeGM96** [comment]
Por lo tanto, la información completa de un reto sería:
- IP: dirección de la máquina a la que tenemos que acceder.
- Puerto: puerto por el cual se accederá a la máquina objetivo.
- SO: Tipo de sistema operativo que contiene la máquina objetivo.
- Versión: Versión del sistema operativo de la máquina objetivo.
- Flag: Campo de texto que representa el objetivo del reto CTF.

**Comment by chelunike** [comment]
@JaimeGM96 Si, eso sería todo.

**Comment by chelunike** [comment]
Resuelto en el Pull Request #11
