### ISSUE TITLE
No disponemos de una entidad que albergue la lógica de negocio

### ISSUE THREAD

**Issue by JaimeGM96** [chelunike/didactic-chainsaw#12]

**Comment by JaimeGM96** [comment]
Una vez representados los objetos valor Ruta y Cve, necesitamos crear una entidad que nos permita realizar las búsquedas que se comenta en la documentación, es decir, una entidad que contenga la lógica de negocio.

**Comment by chelunike** [comment]
Resuelto en el Pull Request #11
