### ISSUE TITLE
Elección de lenguaje de programación

### ISSUE THREAD

**Issue by JaimeGM96** [chelunike/didactic-chainsaw#4]
Hola! Tengo que trabajar sobre tu objetivo 2, encantado!

Lo primero de todo es elegir en qué lenguaje de programación vamos a trabajar. De los posibles lenguajes que existen, me ha interesado Go, por su rapidez y por su auge en los últimos años. Es un lenguaje que nos servirá para programar la aplicación web que comentas en la documentación. ¿Qué te parece? Si prefieres otro lenguaje házmelo saber.

**Comment by chelunike** [comment]
@JaimeGM96 Lo cierto es que también había pensado en Go y en Rust como posibles lenguajes puesto que le tengo ganas a ambos de incarle el diente. Pero creo que al problema le vendría mejor algo con clases para definir entidades y gestionar los datos con una estructura estándar. Por lo cual pense en Python o en Ruby, más bien este último que lo tengo un poco olvidado. Además, y pese al desprecio inicial que tiene mucha gente, Java podría ser otra opción y ser de ayuda un fuerte tipado a parte de que sería más rápido a la hora de realizar peticiones.

**Comment by JaimeGM96** [comment]
Yo me siento cómodo con Java, ¿quieres que sea ese el lenguaje que usemos?

**Comment by chelunike** [comment]
@JaimeGM96 Me gusta mucho ti iniciativa y yo también tengo conocimentos de Java como para seguir adelante. Y también tenemos el beneficio de la portabilidad.

**Comment by chelunike** [comment]
@JaimeGM96 Podemos cerrar este tema lo antes posible para poder continuar.

**Comment by chelunike** [comment]
Resuelto en el PullRequest #11
