### ISSUE TITLE
No sabemos como representar un CTF

### ISSUE THREAD

**Issue by JaimeGM96** [chelunike/didactic-chainsaw#5]
Relacionado con #2.

**Comment by JaimeGM96** [comment]
¿Un CTF contiene un flag?

**Comment by chelunike** [comment]
@JaimeGM96 En un CTF, hay varios retos y para cada reto hay que encontrar una flag.

**Comment by JaimeGM96** [comment]
¿Entonces ahora mismo no necesitamos crear la estructura de un CTF?

**Comment by chelunike** [comment]
No necesitamos representantar todo un CTF, puesto que el problema no se tiene siempre con todos los retos, pero a lo mejor si se puede plantear una representación de un reto.

**Comment by chelunike** [comment]
Voy a cerrar el Issue puesto que no resulta necesario representar todo un ctf, sino representar un reto y esto se solucionara en #10 :)

**Comment by chelunike** [comment]
Voy a cerrar el Issue puesto que no resulta necesario representar todo un ctf, sino representar un reto y esto se solucionara en #10  :)
