### ISSUE TITLE
No sabemos como representar un CVE

### ISSUE THREAD

**Issue by JaimeGM96** [chelunike/didactic-chainsaw#6]
Relacionado con #2.

**Comment by JaimeGM96** [comment]
Una posible representación de un CVE puede ser la siguiente:
- Código de referencia: código que entre otras cosas, indica el año de descubrimiento de la vulnerabilidad.
- Autor: persona que descubrió la vulnerabilidad.
- Descripción: descripción de como se ha descubierto la vulnerabilidad.
- Referencias: Enlaces de referencia al código donde se demuestra y soluciones al mismo.

@chelunike ¿Qué te parecen estos términos?

**Comment by chelunike** [comment]
@JaimeGM96  Todo eso lo veo perfecto, creo que no se le escapa nada. A lo mejor podemos guardar una referencia a la fuente original de la información del CVE.

**Comment by chelunike** [comment]
Resuelto en el Pull Request #11
