### ISSUE TITLE
No sabemos como representar un flag

### ISSUE THREAD

**Issue by JaimeGM96** [chelunike/didactic-chainsaw#8]
Relacionado con #2 y #5.

**Comment by JaimeGM96** [comment]
Una posible representación de un flag puede ser la siguiente:
- Tipo: nos indica el tipo de flag que es. En nuestro caso, haciendo referencia a lo nombrado en #2, los tipos de flag que queremos representar son web y pwn.
- Dirección IP: dirección de la máquina a la que tenemos que acceder.
- Puerto: puerto por el cual accederemos a la máquina objetivo.

@chelunike ¿Cómo ves estos datos?

**Comment by chelunike** [comment]
@JaimeGM96 La flag siempre va a ser un pequeño texto con un formato reconocible, normalmente suele ser `flag{...}`

**Comment by JaimeGM96** [comment]
Entonces tendría un campo de texto para el nombre, información de la máquina como por ejemplo:
- SO: Ubuntu
- Versión: 22.04.3 LTS
y no se cómo ves almacenar la dirección ip y el puerto. @chelunike

**Comment by chelunike** [comment]
@JaimeGM96 Podríamos guardar la información respecto a ip y puerto si la usáramos para intentar hacer una detección automática de versión.

**Comment by chelunike** [comment]
@JaimeGM96, creo que la representación de la flag que simplemente va a ser un texto que es simplemente información de un reto, se podría dejar simplemente en el Issue #10.

**Comment by JaimeGM96** [comment]
Si solo es una cadena de texto me parece bien!

**Comment by chelunike** [comment]
Se cierra porque se resuelve en #10
